### ISSUE TITLE
Edit Order page & Responsive

### ISSUE THREAD

**Issue by thadk** [codefordc/us-congress-pizza-flag-tracker-frontend#79]
<img width="427" alt="image" src="https://user-images.githubusercontent.com/283343/159814551-8432840a-55fb-4250-90f1-068f64b52048.png">

- QR Code shape and text (remove the visible code), try to remove `width: 50%;`
- Make "Add Order" adjust to "Edit Order" when appropriate. 
     - Adjust using these two pieces https://github.com/codefordc/us-congress-pizza-flag-tracker-frontend/blob/main/src/components/orderForm.js#L155 and https://github.com/codefordc/us-congress-pizza-flag-tracker-frontend/blob/main/src/components/orderForm.js#L134
     - Hover color on `.orderLinks` for contrast

**Comment by mertbagt** [comment]
- [x] QR Code shape and text (remove the visible code), try to remove `width: 50%;`
- [x] Make "Add Order" adjust to "Edit Order" when appropriate.
     - [x] Adjust using these two pieces https://github.com/codefordc/us-congress-pizza-flag-tracker-frontend/blob/main/src/components/orderForm.js#L155 and https://github.com/codefordc/us-congress-pizza-flag-tracker-frontend/blob/main/src/components/orderForm.js#L134

- [ ] Hover color on `.orderLinks` for contrast

![image](https://user-images.githubusercontent.com/73559781/161144444-c36fe12b-fc03-4deb-8624-22ee476e1976.png)

it appears that provisions were made to give :hover, :focus, and :active functionality but they currently seem to just do the same thing that .orderLinks is doing instead of their own thing.

Presumably, move them to their own line:

```
.orderLinks:hover, .orderLinks,:focus, .orderLinks:active {
  variousColorOptions: someContrastingColor
}
```
